apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: memberlist-example
build:
  local:
    useBuildkit: true
  artifacts:
  - image: memberlist-example
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
